name: .NET Core (build & publish pre-release)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: .NET core build
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 5.0.100-preview.4.20202.8
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish Pre-release
      id: publish_nuget
      uses: rohith/publish-nuget@v2.4.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: MessageManager.csproj
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
