name: .NET Core (build pull request)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1.1.0
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: |
          enhancement
          automerge

    - uses: actions/checkout@v2
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    - name: Restore
      run: dotnet restore
      shell: bash
    # we must build the msbuild task 1st in order to prevent build failures
    # due to ProjectReferencing it.
    - name: Build with dotnet
      run: |
        cd GitBuildInfo
        dotnet build --configuration Release --no-restore
        cd ..
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build
      shell: bash

    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'AraHaan' || github.actor == 'CatGirlsAreLife' || github.actor == 'Raitou' || github.actor == 'JunichiSama' || github.actor == 'xioke' || github.actor == 'Elskom-gitsync'
      with:
        # I think this must stay the same.
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'AraHaan' || github.actor == 'CatGirlsAreLife' || github.actor == 'Raitou' || github.actor == 'JunichiSama' || github.actor == 'xioke' || github.actor == 'Elskom-gitsync'
      with:
        github_token: ${{ secrets.GITSYNC_TOKEN }}
        labels: |
          enhancement
          automerge
